apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-kustomization
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: nginx-gitrepo
  path: .
  prune: true
  wait: true
  timeout: 2m